# Level 1 - Task 1: Data Cleaning & Preprocessing

## Step 1: Import Required Libraries

In [ ]:
import pandas as pd

## Step 2: Load the Iris Dataset

In [2]:
df = pd.read_csv("C:/Users/asdf/Downloads/1) iris.csv")

## Step 3: Display the First Five Rows

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Step 4: Check Dataset Shape

In [4]:
df.shape

(150, 5)

## Step 5: Display Column Names

In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

## Step 6: Check Dataset Information

In [6]:
df.info

<bound method DataFrame.info of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

## Step 7: Generate Summary Statistics

In [7]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## Step 8: Check for null values

In [8]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

## Step 9: Check for Duplicate Rows

In [9]:
df.duplicated().sum()

np.int64(3)

## Step 10: Remove Duplicate Rows

In [10]:
df=df.drop_duplicates()

## Step 11: Check for Duplicate Rows

In [11]:
df.duplicated().sum()

np.int64(0)

## Step 12: Check Data Types

In [12]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

## Step 13: Check Unique Values

In [14]:
df["species"].unique()

<ArrowStringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

## Step 14: Save the Cleaned Dataset

In [16]:
df.to_csv("iris_cleaned.csv", index=False)

In [17]:
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!